name: Lint Code Base

on: [pull_request]

jobs:
  lint:
    name: Run Psscriptanalyzer
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint PowerShell Code
        uses: github/PowerShell/Psscriptanalyzer
        with:
          sendComment: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}